package io.github.haburashi76.music_maker

import org.bukkit.Sound
import org.bukkit.Sound.*

enum class NoteType(val sound: Sound) {
    HARP(BLOCK_NOTE_BLOCK_HARP),
    BASS(BLOCK_NOTE_BLOCK_BASS),
    SNARE(BLOCK_NOTE_BLOCK_SNARE),
    HAT(BLOCK_NOTE_BLOCK_HAT),
    BASEDRUM(BLOCK_NOTE_BLOCK_BASEDRUM),
    BELL(BLOCK_NOTE_BLOCK_BELL),
    FLUTE(BLOCK_NOTE_BLOCK_FLUTE),
    CHIME(BLOCK_NOTE_BLOCK_CHIME),
    GUITAR(BLOCK_NOTE_BLOCK_GUITAR),
    XYLOPHONE(BLOCK_NOTE_BLOCK_XYLOPHONE),
    IRON_XYLOPHONE(BLOCK_NOTE_BLOCK_IRON_XYLOPHONE),
    COW_BELL(BLOCK_NOTE_BLOCK_COW_BELL),
    DIDGERIDOO(BLOCK_NOTE_BLOCK_DIDGERIDOO),
    BIT(BLOCK_NOTE_BLOCK_BIT),
    BANJO(BLOCK_NOTE_BLOCK_BANJO),
    PLING(BLOCK_NOTE_BLOCK_PLING);
}